### ISSUE TITLE
[BUG] Exception cannot be caught when Request-VCFToken cmdlet is supplied with incorrect credentials

### ISSUE THREAD

**Issue by MadhusudanMI** [vmware/powershell-module-for-vmware-cloud-foundation#148]
### Code of Conduct

- [X] I have read and agree to the project's Code of Conduct.

### PowerVCF

2.1.7

### VMware Cloud Foundation

4.3.1.1

### PowerShell

12.0

### Guest Operating System

Windows

### Description

We have an automation script which is invoking Request-VCFToken cmdlet to connect to SDDC Manager. When incorrect credentials are supplied to the script, error message gets displayed on the console. Our requirement is to catch the exception and customise the message to the user. 

### Expected Behavior

Expecting to catch the exception and customise the error message to the user of our script. 

### Actual Behavior

Exception is not getting caught. In stead the error message gets displayed on the console. 

### Steps to Reproduce

Write a function which takes credentials of SDDC manager as parameters and invokes Request-VCFToken inside the function that catches exception for incorrect credentials. When the function is called with incorrect credentials error message gets displayed on the console instead of the exception getting caught.

**Comment by tenthirtyam** [comment]
Hi, @MadhusudanMI.

Can you please confirm and update the version of Power**Shell**, vs Power**CLI**?

e.g Windows PowerShell 5.1, PowerShell Core 7.2.4, etc

**Ryan Johnson**
Staff II Solutions Architect | VMware, Inc.

**Comment by LifeOfBrianOC** [comment]
Hi @MadhusudanMI please test with branch dev-boc-148 before we merge to main. You should be able to do the following or similar in your code
![image](https://user-images.githubusercontent.com/10587010/177207303-0d6f4105-a6dd-4113-a701-466ad26c58ae.png)

**Comment by MadhusudanMI** [comment]
Hi @LifeOfBrianOC,

That worked for me. 

Thanks,
Madhusudan M I
