### ISSUE TITLE
[ENHANCEMENT] Add support in the 1.x branch (VCF 3.x) for Start-VCFUpgrade

### ISSUE THREAD

**Issue by LifeOfBrianOC** [vmware/powershell-module-for-vmware-cloud-foundation#182]
### Code of Conduct

- [X] I have read and agree to the project's Code of Conduct.

### Description

Add support in the 1.x branch (VCF 3.x) for Start-VCFUpgrade. Requested by the internal VCF migration team

### Use Case(s)

To be used as part of automating 3x to 4x VCF

### Potential Configuration

New cmdlet

**Comment by GaryJBlake** [comment]
Addressed with #183
