### ISSUE TITLE
Exception cannot be caught when `Request-VCFToken` cmdlet is supplied with incorrect credentials

### ISSUE THREAD

**Issue by MadhusudanMI-PSH** [vmware/powershell-module-for-vmware-cloud-foundation#187]
### Code of Conduct

- [X] I have read and agree to the project's Code of Conduct.

### PowerVCF

2.2.0

### VMware Cloud Foundation

4.4

### PowerShell

5.1

### Guest Operating System

Windows Server 2012 R2

### Description

https://github.com/vmware/powershell-module-for-vmware-cloud-foundation/issues/148 - This was the bug that I had raised on the same issue. Today the issue still persists. 

### Expected Behavior

Should be able to catch the exception and based on the exception should be able to display custom message instead the exception getting displayed as shown in the attachment.

### Actual Behavior

Exception gets displayed as is without being caught. 

### Steps to Reproduce

Supply Request-VCFToken cmdlet with incorrect credentials and execute. 

### Screenshots

![RequestVCFTokenIssue](https://user-images.githubusercontent.com/121003619/208353457-15cb1312-9427-4a5c-89c5-0355ff5b0c12.png)

**Comment by tenthirtyam** [comment]
This can be resolved with the following:

```powershell
    Catch {
        if ($_.ErrorDetails.Message) {
            Write-Error $_.ErrorDetails.Message
        } else {
            Write-Error $_
        }
    }
```

The result is that it displays the specific error message:

**Example**: HTTP 401 

```powershell
PS F:\VMware.CloudFoundation.Reporting> Request-VCFToken -fqdn sfo-vcf01.sfo.rainpole.io -username administrator@vsphere.local -password ThisIsNotTheCorrectPassword
Request-VCFToken : The remote server returned an error: (401) Unauthorized.
At line:1 char:1
+ Request-VCFToken -fqdn sfo-vcf01.sfo.rainpole.io -username administra ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Write-Error], WriteErrorException
    + FullyQualifiedErrorId : Microsoft.PowerShell.Commands.WriteErrorException,Request-VCFToken
```

**Comment by tenthirtyam** [comment]
Better yet, update `Request-VCFToken` to use the module's `esponseException` function: 

```powershell
    Catch {
        ResponseException -object $_
    }
```

Example: HTTP 401

```powershell
Script File:        Line: 68
Relevant Command:  $response = Invoke-RestMethod -Method POST -Uri $uri -Headers $headers -body $body
Target Uri:         https://sfo-vcf01.sfo.rainpole.io/v1/tokens
Exception Message: The remote server returned an error: (401) Unauthorized.
````
