### ISSUE TITLE
Remove depreciated function aliases

### ISSUE THREAD

**Issue by burnsjared0415** [vmware/powershell-module-for-vmware-cloud-foundation#264]
### Code of Conduct

- [X] I have read and agree to the project's Code of Conduct.

### Description

Remove all Alias references in PowerVCF as the Functions have been removed

### Use Case(s)

Clean up all Alias information for a cleaning file

### Potential Configuration

Before:
https://github.com/vmware/powershell-module-for-vmware-cloud-foundation/blob/af10d79bd293fa86cc4605a37a436ac53d34d801/PowerVCF.psm1#L2553-L2555

After:
If statement will be removed

Before:
https://github.com/vmware/powershell-module-for-vmware-cloud-foundation/blob/af10d79bd293fa86cc4605a37a436ac53d34d801/PowerVCF.psm1#L2597-L2598

After:
```powershell
Export-ModuleMember -Function New-VCFCommissionedHost
```

**Comment by tenthirtyam** [comment]
Scope:

- Remove `Commission-VCFHost` Alias from `New-VCFCommissionedHost`
- Remove `Decommission-VCFHost` Alias from `Remove-VCFCommissionedHost`
- Remove `Get-VCFNsxManagerCluster` Alias from `Get-VCFNsxtCluster`
- Remove `Get-VCFNsxEdgeCluster` Alias from `Get-VCFEdgeCluster`
- Remove `New-VCFNsxEdgeCluster` Alias from `New-VCFEdgeCluster`
