### ISSUE TITLE
Workload Domain Validation via New-VCFWorkloadDomain does not properly handle multiple errors

### ISSUE THREAD

**Issue by lamw** [vmware/powershell-module-for-vmware-cloud-foundation#266]
### Code of Conduct

- [X] I have read and agree to the project's Code of Conduct.

### PowerVCF

2.4.1.1000

### VMware Cloud Foundation

5.1

### PowerShell

7.4.1

### Guest Operating System

macOS Silicon (14.2.1)

### Description

While using the `New-VCFWorkloadDomain` to validate my workload domain JSON, I ran into the following error, which didn't provide anything useful ...

```console
$workloadDeployment = New-VCFWorkloadDomain -json ./workload-domain.json
New-VCFWorkloadDomain: The validation task commpleted the run with the following problems:
Script File:       /Users/wlam/.local/share/powershell/Modules/PowerVCF/2.4.1.1000/PowerVCF.psm1 Line: 1951
Relevant Command:  Write-Error $response.validationChecks.errorResponse.message
Target Uri:
Exception Message: Cannot convert 'System.Object[]' to the type 'System.Management.Automation.ErrorRecord' required by parameter 'ErrorRecord'. Specified method is not supported.
Error Message:
```

It wasn't until I was directed to use the SDDC Manager API (via Developer Center), did we learn that Validation API is working as expected and includes specific reason for the validation failure (e.g. incorrect input). 

At first glance, I saw that we save the output to `$response` variable and simply output it and it doesn't iterate through the actual API response, so I figured that was the issue. 

I then went to repro the issue to report but then found a slight nuance, which is that when there's a single error, it is properly reported BUT when there's multiple errors and in this case, the API response can be one or more, then the issue above is reached. 

### Expected Behavior

We should ensure that the response for a given API is properly understood, whether its a single or multiple results, as the underlying API did the right thing but the function made an assumption that it only had a single response, so when multiple responses (due to multiple pre-check failures), it dumped some unknown text rather than the actual pre-check results

### Actual Behavior

Describe above

### Steps to Reproduce

Take a working workload domain JSON, make a typo for gateway and see that pre-check information is properly displayed in console. Now make two or more typos (e.g. gateway) and see that it no longer properly shows the pre-check error but the one reported above

**Comment by LifeOfBrianOC** [comment]
This is easily fixed by changing the Write-Error on line 1951 to a Write-Output. That will produce the following

<img width="1073" alt="image" src="https://github.com/vmware/powershell-module-for-vmware-cloud-foundation/assets/10587010/7563214a-9379-41ae-a52a-2d908ce3dfe7">

We could also enhance the output to include the following if its deemed useful

<img width="1073" alt="image" src="https://github.com/vmware/powershell-module-for-vmware-cloud-foundation/assets/10587010/d5d8840f-37c0-4a57-840a-ba7be177468e">
