### ISSUE TITLE
Include Content-Type in the VCF Headers variable

### ISSUE THREAD

**Issue by lamw** [vmware/powershell-module-for-vmware-cloud-foundation#286]
### Code of Conduct

- [X] I have read and agree to the project's Code of Conduct.

### PowerVCF

2.4.1

### VMware Cloud Foundation

5.2.0

### PowerShell

7.4.3

### Guest Operating System

macOS

### Description

I've ran into some strange errors when Content-Type header isn't added to headers when invoking VCF API, typically you'll want to have this, so no default are assumed, which seemed to have been my case when calling some of the new VCF 5.2 API

As workaround, I've manually added `$headers.add("Content-Type","application/json")` which resolves the issue for some function development I'm doing

### Expected Behavior

No additional headers are needed 

### Actual Behavior

The following error is thrown by PowerVCF:

```console
{
  "errorCode": "VCF_RUNTIME_ERROR",
  "arguments": [],
  "message": "Something went wrong. Please retry or contact the service provider and provide the reference token.",
  "referenceToken": "3KUN0T"
}
```

When looking at the `vcf-commonsvcs.log:`, I see the following:

vcf-commonsvcs.log:, message=Content-Type 'application/x-www-form-urlencoded' is not supported., path=/v1/domains/6ca52d6b-9292-4baf-ab97-75c3a74d4bf2/compliance-audits}

### Steps to Reproduce

N/A

**Comment by alagoutte** [comment]
It is an issue with PowerShell 7.4.3 about missing content-type
